version: "3"
services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php-server1
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./html:/var/www/html
volumes:
  html: {}
